# Change these first
owner: Sheemap # Your GitHub organization or username, where this repository lives
repo: snazcat-upptime # The name of this repository

sites:
  - name: Foundry
    url: $FOUNDRY
  - name: Plex
    url: http://snazcat.com:32400
    expectedStatusCodes:
      - 200
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /snazcat-upptime
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Snazcat Upptime"
  introTitle: "Snazcat uptime monitoring"
  introMessage: "This is the snazcat uptime page which shows historical uptime and notifies if things are down"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
